# Generated by Django 3.1.6 on 2021-02-10 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlog',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 16, 40, 46, 406693)),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 16, 40, 46, 406720)),
        ),
    ]
